// <auto-generated />
using System;
using BeeKeeping.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeeKeeping.Migrations
{
    [DbContext(typeof(BeeKeepingDbContext))]
    [Migration("20260515140215_AddPurchaseAttachments")]
    partial class AddPurchaseAttachments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("BeeKeeping.Data.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("BeeKeeping.Data.Models.EquipmentPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeductible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceiptReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TaxYear")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("EquipmentPurchases");
                });

            modelBuilder.Entity("BeeKeeping.Data.Models.Hive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BeeBreed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EstablishedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QueenStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hives");
                });

            modelBuilder.Entity("BeeKeeping.Data.Models.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionsTaken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BroodPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EggsSeen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HiveId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoneyStoresRating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Inspector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LarvaeSeen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NextSteps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PopulationRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueenSeen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemperamentRating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Treatments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("VarroaMiteCheck")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("VarroaMiteCount")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeatherConditions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HiveId");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("BeeKeeping.Data.Models.PurchaseAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentPurchaseId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentPurchaseId");

                    b.ToTable("PurchaseAttachments");
                });

            modelBuilder.Entity("BeeKeeping.Data.Models.EquipmentPurchase", b =>
                {
                    b.HasOne("BeeKeeping.Data.Models.Equipment", "Equipment")
                        .WithMany("Purchases")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("BeeKeeping.Data.Models.Inspection", b =>
                {
                    b.HasOne("BeeKeeping.Data.Models.Hive", "Hive")
                        .WithMany("Inspections")
                        .HasForeignKey("HiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hive");
                });

            modelBuilder.Entity("BeeKeeping.Data.Models.PurchaseAttachment", b =>
                {
                    b.HasOne("BeeKeeping.Data.Models.EquipmentPurchase", "EquipmentPurchase")
                        .WithMany("Attachments")
                        .HasForeignKey("EquipmentPurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentPurchase");
                });

            modelBuilder.Entity("BeeKeeping.Data.Models.Equipment", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("BeeKeeping.Data.Models.EquipmentPurchase", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("BeeKeeping.Data.Models.Hive", b =>
                {
                    b.Navigation("Inspections");
                });
#pragma warning restore 612, 618
        }
    }
}
